version: '3'
services:
  node:
    build: ./.docker/node
    command: yarn start
    volumes:
      - .:/home/services
    working_dir: /home/services
    ports:
      - ${DOCKER_NODE_PORT}:${DOCKER_NODE_PORT}
    env_file:
      - .env
